artifact_location: file:///Users/hiraokatatsuru/Library/Mobile%20Documents/com~apple~CloudDocs/postal-operation-shift-management-system/mlruns/334232251085137909
creation_time: 1764540471561
experiment_id: '334232251085137909'
last_update_time: 1764540471561
lifecycle_stage: active
name: posms_kakitome
