artifact_location: file:///Users/hiraokatatsuru/Library/Mobile%20Documents/com~apple~CloudDocs/postal-operation-shift-management-system/mlruns/286424433526374346
creation_time: 1764540504146
experiment_id: '286424433526374346'
last_update_time: 1764540504146
lifecycle_stage: active
name: posms_nenga_delivery
