artifact_location: file:///Users/hiraokatatsuru/Library/Mobile%20Documents/com~apple~CloudDocs/postal-operation-shift-management-system/mlruns/660777268308289810
creation_time: 1764540494814
experiment_id: '660777268308289810'
last_update_time: 1764540494814
lifecycle_stage: active
name: posms_ems
