# docker-compose.dev.yml
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ghcr.io/hiraokatatsuru/posms-app:dev
    command: ["tail","-f","/dev/null"]   # ← 常駐
    volumes: [.:/app]
    working_dir: /app

