name: posms
services:
  # ---------- PostgreSQL ----------
  db:
    image: postgres:16-alpine
    container_name: posms-db
    restart: always
    environment:
      POSTGRES_USER: posms
      POSTGRES_DB: posms
      # ← 初期化時のみ有効。trust 認証でパスワードなし起動（開発/CI専用）
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    ports: ["127.0.0.1:15432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U posms -d posms"]
      interval: 5s
      timeout: 3s
      retries: 20

  # ---------- MLflow ----------
  mlflow:
    image: ghcr.io/mlflow/mlflow            
    container_name: posms-mlflow
    command: ["mlflow","server",
            "--backend-store-uri","sqlite:////mlruns/mlflow.db",
            "--default-artifact-root","/mlruns",
            "-h","0.0.0.0","-p","5000"]
    volumes: [mlruns:/mlruns]
    ports: ["127.0.0.1:15000:5000"]

  # ---------- Prefect OSS (UI + API) ----------
  prefect:
    image: prefecthq/prefect:2.18-python3.11
    container_name: posms-prefect
    command: ["prefect","server","start","--host","0.0.0.0","--port","4200"]
    volumes: [prefect_data:/root/.prefect]     # 実行履歴を永続化
    ports: ["127.0.0.1:4200:4200"]

  # ---------- アプリ本体 ----------
  app:
    image: ghcr.io/tatsuruhiraoka/posms-app:latest
    pull_policy: always
    container_name: posms-app
    restart: on-failure
    environment:
      # 内部ネットワーク参照（.env 不要）
      PREFECT_API_URL: http://prefect:4200/api
      DATABASE_URL: postgresql+psycopg2://posms@db:5432/posms
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_EXPERIMENT_NAME: posms
      ENVIRONMENT: development
      LOG_LEVEL: INFO
    depends_on:
      db:
        condition: service_healthy
      mlflow:
        condition: service_started
      prefect:
        condition: service_started
    volumes: [.:/app]
    working_dir: /app
    # 実行コマンドは Dockerfile の CMD に記述
    # 例) python posms/flows/monthly_flow.py

volumes:
  db_data:
  mlruns:
  prefect_data:
