artifact_uri: file:///Users/hiraokatatsuru/Library/Mobile%20Documents/com~apple~CloudDocs/postal-operation-shift-management-system/mlruns/272322461023719724/005d6f4205774eeda5eb94aa0e5cfb15/artifacts
end_time: 1764540494756
entry_point_name: ''
experiment_id: '272322461023719724'
lifecycle_stage: active
run_id: 005d6f4205774eeda5eb94aa0e5cfb15
run_name: intelligent-cod-761
run_uuid: 005d6f4205774eeda5eb94aa0e5cfb15
source_name: ''
source_type: 4
source_version: ''
start_time: 1764540491067
status: 3
tags: []
user_id: hiraokatatsuru
