artifact_uri: file:///Users/hiraokatatsuru/Library/Mobile%20Documents/com~apple~CloudDocs/postal-operation-shift-management-system/mlruns/329043204161350914/86903dcf10db4db8a41a13dfcfc89f29/artifacts
end_time: 1764540158422
entry_point_name: ''
experiment_id: '329043204161350914'
lifecycle_stage: active
run_id: 86903dcf10db4db8a41a13dfcfc89f29
run_name: nosy-gnu-87
run_uuid: 86903dcf10db4db8a41a13dfcfc89f29
source_name: ''
source_type: 4
source_version: ''
start_time: 1764540154716
status: 3
tags: []
user_id: hiraokatatsuru
