artifact_uri: file:///Users/hiraokatatsuru/Library/Mobile%20Documents/com~apple~CloudDocs/postal-operation-shift-management-system/mlruns/329043204161350914/abcadd214f864207bb818584a3116edd/artifacts
end_time: 1764540471503
entry_point_name: ''
experiment_id: '329043204161350914'
lifecycle_stage: active
run_id: abcadd214f864207bb818584a3116edd
run_name: wise-penguin-779
run_uuid: abcadd214f864207bb818584a3116edd
source_name: ''
source_type: 4
source_version: ''
start_time: 1764540468905
status: 3
tags: []
user_id: hiraokatatsuru
