artifact_location: file:///Users/hiraokatatsuru/Library/Mobile%20Documents/com~apple~CloudDocs/postal-operation-shift-management-system/mlruns/716229111608289512
creation_time: 1764540484607
experiment_id: '716229111608289512'
last_update_time: 1764540484607
lifecycle_stage: active
name: posms_tokutei_kiroku
