artifact_location: file:///Users/hiraokatatsuru/Library/Mobile%20Documents/com~apple~CloudDocs/postal-operation-shift-management-system/mlruns/272322461023719724
creation_time: 1764540491066
experiment_id: '272322461023719724'
last_update_time: 1764540491066
lifecycle_stage: active
name: posms_e_packet
