artifact_uri: file:///Users/hiraokatatsuru/Library/Mobile%20Documents/com~apple~CloudDocs/postal-operation-shift-management-system/mlruns/473277832423795085/af7b4e07bec141069ce24f7e69388beb/artifacts
end_time: 1764540504087
entry_point_name: ''
experiment_id: '473277832423795085'
lifecycle_stage: active
run_id: af7b4e07bec141069ce24f7e69388beb
run_name: crawling-perch-317
run_uuid: af7b4e07bec141069ce24f7e69388beb
source_name: ''
source_type: 4
source_version: ''
start_time: 1764540500443
status: 3
tags: []
user_id: hiraokatatsuru
