artifact_location: file:///Users/hiraokatatsuru/Library/Mobile%20Documents/com~apple~CloudDocs/postal-operation-shift-management-system/mlruns/156674675143461472
creation_time: 1764540477866
experiment_id: '156674675143461472'
last_update_time: 1764540477866
lifecycle_stage: active
name: posms_letterpack_light
