artifact_uri: file:///Users/hiraokatatsuru/Library/Mobile%20Documents/com~apple~CloudDocs/postal-operation-shift-management-system/mlruns/334232251085137909/cdcc7e042f69478593fa5d46dee3d122/artifacts
end_time: 1764540474426
entry_point_name: ''
experiment_id: '334232251085137909'
lifecycle_stage: active
run_id: cdcc7e042f69478593fa5d46dee3d122
run_name: smiling-stork-633
run_uuid: cdcc7e042f69478593fa5d46dee3d122
source_name: ''
source_type: 4
source_version: ''
start_time: 1764540471562
status: 3
tags: []
user_id: hiraokatatsuru
