artifact_location: file:///Users/hiraokatatsuru/Library/Mobile%20Documents/com~apple~CloudDocs/postal-operation-shift-management-system/mlruns/269619312197250200
creation_time: 1764540480684
experiment_id: '269619312197250200'
last_update_time: 1764540480684
lifecycle_stage: active
name: posms_letterpack_plus
