artifact_location: file:///Users/hiraokatatsuru/Library/Mobile%20Documents/com~apple~CloudDocs/postal-operation-shift-management-system/mlruns/122647475666054799
creation_time: 1764540488237
experiment_id: '122647475666054799'
last_update_time: 1764540488237
lifecycle_stage: active
name: posms_yu_pack
