artifact_uri: file:///Users/hiraokatatsuru/Library/Mobile%20Documents/com~apple~CloudDocs/postal-operation-shift-management-system/mlruns/156674675143461472/d1997331a5a94efbac47fb7e9b86b21a/artifacts
end_time: 1764540480627
entry_point_name: ''
experiment_id: '156674675143461472'
lifecycle_stage: active
run_id: d1997331a5a94efbac47fb7e9b86b21a
run_name: charming-wolf-986
run_uuid: d1997331a5a94efbac47fb7e9b86b21a
source_name: ''
source_type: 4
source_version: ''
start_time: 1764540477867
status: 3
tags: []
user_id: hiraokatatsuru
