artifact_location: file:///Users/hiraokatatsuru/Library/Mobile%20Documents/com~apple~CloudDocs/postal-operation-shift-management-system/mlruns/660204372025621067
creation_time: 1757122985554
experiment_id: '660204372025621067'
last_update_time: 1757122985554
lifecycle_stage: active
name: posms
